export const SUBSCRIPTIONS = {
  TRAINER: 'trainer',
  SPORTPLAYER: 'sportplayer',
}

export const SUBSCRIPTION_UI = {
  [SUBSCRIPTIONS.TRAINER]: 'Entrenador',
  [SUBSCRIPTIONS.SPORTPLAYER]: 'Deportista',
}

export const LIST_OF_SUBS = [SUBSCRIPTIONS.TRAINER, SUBSCRIPTIONS.SPORTPLAYER]
